///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

   static const String cleaning = 'assets/cleaning.png';
   static const String repairing = 'assets/tools.png';
   static const String painting = 'assets/painting.png';

}
